/**:
  ros__parameters:
    all_episodes_categorical:
    - data_key: time_diff
      differentiate: local_planner
      plot_args: {}
      plot_key: bar
      save_name: cat_time_diff
      title: time_diff
    - data_key: angle_over_length
      differentiate: local_planner
      plot_args: {}
      plot_key: bar
      save_name: cat_angle_over_length
      title: Angle Over Length
    - data_key: path_length
      differentiate: local_planner
      plot_args: {}
      plot_key: bar
      save_name: cat_path_length
      title: Path Length
    all_episodes_distribution:
    - data_key: time_diff
      differentiate: local_planner
      plot_args: {}
      plot_key: box
      save_name: cat_agg_time_diff
      title: Time
    - data_key: angle_over_length
      differentiate: local_planner
      plot_args: {}
      plot_key: box
      save_name: cat_agg_angle_over_length
      title: Angle Over Length
    - data_key: path_length
      differentiate: local_planner
      plot_args: {}
      plot_key: box
      save_name: cat_agg_path_length
      title: Path Length
    datasets:
    - 14-02-2023_16-50-54_jackal_0_0
    - 14-02-2023_16-59-41_jackal_0_0
    - 14-02-2023_17-04-33_jackal_0_0
    - 14-02-2023_17-06-48_jackal_0_0
    - 14-02-2023_17-09-13_jackal_0_0
    - 14-02-2023_17-56-15_jackal_0_0
    - 14-02-2023_17-58-50_jackal_0_0
    - 14-02-2023_18-04-41_jackal_0_0
    - 14-02-2023_18-28-40_jackal_0_0
    episode_plots_for_namespaces:
      desired_results: GOAL_REACHED
      differentiate: local_planner
      save_name: path
      should_add_collisions: false
      should_add_obstacles: false
      title: Path
    results:
      differentiate: local_planner
      plot: true
      plot_args: {}
      save_name: results
      title: Results
    save_location: eval_iros_2023
    show_plots: false
    single_episode_distribution:
    - data_key: curvature
      differentiate: local_planner
      episode: 1
      plot_args: {}
      plot_key: box
      save_name: dist_episode_curvature
      title: Curvature
    - data_key: roughness
      differentiate: local_planner
      episode: 1
      plot_args: {}
      plot_key: box
      save_name: dist_episode_roughness
      title: Roughness
    - data_key: path_length_values
      differentiate: local_planner
      episode: 1
      plot_args: {}
      plot_key: box
      save_name: dist_episode_path_length_values
      title: Path Length
    - data_key: acceleration
      differentiate: local_planner
      episode: 1
      plot_args: {}
      plot_key: box
      save_name: dist_episode_acceleration
      title: Acceleration
    - data_key: jerk
      differentiate: local_planner
      episode: 1
      plot_args: {}
      plot_key: box
      save_name: dist_episode_jerk
      title: Jerk
    - data_key: velocity
      differentiate: local_planner
      episode: 1
      plot_args: {}
      plot_key: box
      save_name: dist_episode_velocity
      title: Velocity
    single_episode_line:
    - data_key: curvature
      differentiate: local_planner
      episode: 1
      plot_args:
        xlabel: Time in seconds
      save_name: episode_curvature
      step_size: 2
      title: Curvature
    - data_key: roughness
      differentiate: local_planner
      episode: 1
      plot_args:
        xlabel: Time in seconds
      save_name: episode_roughness
      step_size: 2
      title: Roughness
    - data_key: path_length_values
      differentiate: local_planner
      episode: 1
      plot_args:
        xlabel: Time in seconds
      save_name: episode_path_length_values
      step_size: 2
      title: Path Length
    - data_key: acceleration
      differentiate: local_planner
      episode: 1
      plot_args:
        xlabel: Time in seconds
      save_name: episode_acceleration
      step_size: 2
      title: Acceleration
    - data_key: jerk
      differentiate: local_planner
      episode: 1
      plot_args:
        xlabel: Time in seconds
      save_name: episode_jerk
      step_size: 2
      title: Jerk
    - data_key: velocity
      differentiate: local_planner
      episode: 1
      plot_args:
        xlabel: Time in seconds
      save_name: episode_velocity
      step_size: 2
      title: Velocity
